version: "3"
services:
  syslog:
      build:
        context: '.'
        dockerfile: ./Docker/.Dockerfile
        args:
          DOCKER_REGISTRY_CACHE: "docker.io"
          IMATGE_APLICACIO : "debian:buster-slim"