apiVersion: v1
kind: Pod
metadata:
  name: ap034-pod
  namespace: ap034
  labels:
    app: ap034-frontal
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-pro-worker1
  containers:
  - name: ap034-pod
    image: rancher-sic-local.$domain_stg_ba:8090/ap034_frontal/9.1.3
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
      requests:
        cpu: "1"
        memory: "4Gi"
