apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck-crontab-git
  namespace: rundeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck
      entorn: pro
      tier: crontab-git
      tecnologia: alpine
  template:
    metadata:
      labels:
        app: rundeck
        entorn: pro
        tier: crontab-git
        tecnologia: alpine
    spec:
      containers:
      - name: rundeck-crontab-git
        image: registry.$domain_stg_ba/bcnact-images/crontab:git
        env:
        - name: USER
          value: rundeck
        - name: EMAIL
          value: sistemes.ssi@$domain_pro_ba
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: crontab-git-gitlab-secret
              key: password
        - name: GITLAB_PROJECT
          value: gitlab.$domain_intra_ba/OT-SISCOM/kubernetes/rundeck-scripts.git
        - name: GITLAB_PROJECT_DEVELOP_BRANCH
          value: develop
        - name: GITLAB_PROJECT_RELEASE_BRANCH
          value: release
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"
        volumeMounts:
        #Aquest utilitza el pvc
        - name: data-rundeck-app
          mountPath: /home/
      volumes:
      #Aquest utilitza el pvc
      - name: data-rundeck-app
        persistentVolumeClaim:
          claimName: data-rundeck-app
