apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-a
  namespace: proves
  labels:
      application: apache-a
      entorn: pro
      tecnologia: apache
      tier: frontal
spec:
  storageClassName: k8s-stg-b15390a-corporatives
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi