apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-b
  namespace: proves
  labels:
      application: apache-b
      entorn: pro
      tecnologia: apache
      tier: frontal
spec:
  storageClassName: k8s-stg-b15390b-tecnic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi