apiVersion: v1
kind: Service
metadata:
  name: proves-frontal
  namespace: proves
  labels:
    application: proves-frontal
    entorn: stg
    tier: frontal
    tecnologia: wordpress
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:    
    application: proves-frontal
    entorn: stg
  type: NodePort