apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap034-deployment
  namespace: ap034
  labels:
    app: ap034-frontal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ap034-frontal
  template:
    metadata:
      labels:
        app: ap034-frontal
    spec:
      containers:
      - name: ap034-frontal
        #image: rancher-sic-local.$domain_stg_ba:8090/ap034_frontal/9.1.3
        image: registry.$domain_stg_ba/ap/ap034/frontal:release-9.7.1-11740
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "8Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
