apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-cli-frontal
  namespace: proves
spec:
  replicas: 1
  selector:
    matchLabels:
      application: wp-cli-frontal
      entorn: pro
      tier: frontal
      tecnologia: wordpress
  template:
    metadata:
      labels:
        application: wp-cli-frontal
        entorn: pro
        tier: frontal
        tecnologia: wordpress
    spec:
      containers:
      - name: wp-cli-frontal
        image: registry.$domain_stg_ba/ap/test/frontal-wp-cli:develop-0.0.0-12301
        env:
        - name: APACHE_LogLevel
          value: warn
        - name: APACHE_START
          value: "true"
        - name: BCNACT_ENTORN
          value: STG
        - name: WORDPRESS_ADMIN_EMAIL
          value: posmaster@$domain_pro_ba
        - name: WORDPRESS_ADMIN_PASSWORD
          value: se3GKX9Gzpr15zL8px5TYFC11N3shg3KNav9eRiBmHog3C8uwL9CKp9My5PF
        - name: WORDPRESS_ADMIN_USER
          value: supervisor
        - name: WORDPRESS_DB_HOST
          value: wp-cli-bd
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: 1nternet!
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_TITLE
          value: Example
        - name: WORDPRESS_UPDATE_MAJOR
          value: "false"
        - name: WORDPRESS_UPDATE_MINOR
          value: "false"
        - name: WORDPRESS_URL
          value: wp-cli.$domain_intra_ba
        - name: WORDPRESS_URL_HOME
          value: https://wp-cli.$domain_intra_ba
        - name: WORDPRESS_URL_SITEURL
          value: https://wp-cli.$domain_intra_ba
        - name: WORDPRESS_WWW_HOME
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"
        volumeMounts:
        #Aquest utilitza el pvc
        - name: wp-cli-frontal
          mountPath: /var/www/html
      volumes:
      #Aquest utilitza el pvc
      - name: wp-cli-frontal
        persistentVolumeClaim:
          claimName: wp-cli-frontal
