version: "3"
services:
  rainloop:
    container_name: "rainloop"
    build:
      context: '.'
      dockerfile: ./Docker/.Dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMATGE_BASE : "httpd:latest"
    #volumes:
      #- httpd-data:/usr/local/apache2
    ports:
      - "80:80"
    restart: always
    environment:
      BCNACT_ENTORN: DEV