version: "3"
services:
  mysql8:
    container_name: mysql8
    build:
      context: '.'
      dockerfile: ./Docker/.Dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMATGE_BASEDEDADES : "mysql:8"
    volumes:
      - db_data_2:/var/lib/mysql
      - ./Docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "4836:3306"
    restart: always
    environment:
      BCNACT_ENTORN: DEV
      MYSQL_ROOT_PASSWORD: 1nternet!
      MYSQL_DATABASE: sistemes-dos
      MYSQL_USER: sistemes
      MYSQL_PASSWORD: 1nternet!
volumes:
  db_data_2: {}
networks:
  default:
      name: sistemes