apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proves-dump
  namespace: proves
  labels:
    application: proves-base-de-dades
    entorn: stg
    tier: base-de-dades
spec:
  storageClassName: k8s-stg-b15390a-contingut
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi