apiVersion: v1
kind: Service
metadata:
  name: proves-base-de-dades
  namespace: proves
  labels:
    application: proves-base-de-dades
    entorn: stg
    tier: base-de-dades
    tecnologia: mysql
spec:
  ports:
    - port: 3306
  selector:
    application: proves-base-de-dades
    entorn: stg
  clusterIP: None